#!/bin/sh -e

DAEMON=/usr/sbin/rskkserv
NAME=rskkserv
DESC="SKK dictionary server"

test -x $DAEMON || exit 0

CONF=/etc/rskkserv.conf
PIDFILE="`sed -ne 's/^[ 	]*pid[_ 	]*file[ 	]*=[ 	]*//p' $CONF`"
PIDFILE=${PIDFILE:-/var/run/rskkserv.pid}

case "$1" in
start)
	echo -n "Starting $DESC: $NAME"
	start-stop-daemon --start --oknodo --exec $DAEMON
	echo "."
	;;
stop)
	echo -n "Stopping $DESC: $NAME"
	start-stop-daemon --stop --oknodo --pidfile $PIDFILE --name $NAME
	echo "."
	;;
force-reload|restart)
	echo -n "Restarting $DESC: $NAME"
	start-stop-daemon --stop --oknodo --pidfile $PIDFILE --name $NAME
	sleep 1
	start-stop-daemon --start --oknodo --exec $DAEMON
	echo "."
	;;
*)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
