#!/bin/sh -e

DAEMON=/usr/sbin/rskkserv
NAME=rskkserv
DESC="SKK dictionary server"

test -x $DAEMON || exit 0

CONF=/etc/rskkserv.conf
PIDFILE="`sed -ne 's/^[ 	]*pid[_ 	]*file[ 	]*=[ 	]*//p' $CONF`"
PIDFILE=${PIDFILE:-/var/run/rskkserv.pid}

start() {
	start-stop-daemon --start --exec $DAEMON
}

stop() {
	start-stop-daemon --stop "$@" --pidfile $PIDFILE --name $NAME
}

case "$1" in
start)
	echo -n "Starting $DESC: "
	if start; then
		echo "$NAME."
	fi
	;;
stop)
	echo -n "Stopping $DESC: "
	if stop; then
		echo "$NAME."
	fi
	;;
force-reload|restart)
	echo -n "Restarting $DESC: "
	if stop --quiet && sleep 1; start; then
		echo "$NAME."
	fi
	;;
*)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
